---
- hosts: demo
  user: demo
  tasks:

    - name: remove app
      file: path=/srv/demo/dimension-reduction state=absent

    - name: checkout app
      git: repo=git@github.com:yaodong/dimension-reduction-webapp.git
           dest=/srv/demo/dimension-reduction
           accept_hostkey=True 
           version=release/v0.1
    
    - name: pip update
      pip: name=pip state=latest executable=~/.pyenv/shims/pip
    
    - name: pip install
      pip: requirements=/srv/demo/dimension-reduction/api/requirements.txt executable=~/.pyenv/shims/pip
