# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('method', models.CharField(max_length=64)),
                ('inputs', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('outputs', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('percentage', models.FloatField(default=0.0)),
                ('status', models.IntegerField()),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
