# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='method',
        ),
        migrations.RemoveField(
            model_name='job',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='job',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='job',
            name='outputs',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(default=-2, null=False),
        ),
    ]
