# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_update_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='joboutput',
            unique_together=set([('job', 'name')]),
        ),
    ]
