# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_create_job_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='inputs',
            new_name='params',
        ),
        migrations.AddField(
            model_name='job',
            name='results',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
