# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170502_2111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joboutput',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='joboutput',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='JobOutput',
        ),
    ]
