# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-09 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170502_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='job',
            name='results',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
